const categoryInventory = [
  {
    display_name: "Go Back",
    id: 262,
    damage: 0,
    rarity: "uncommon",
    tag: {
      display: {
        Lore: [],
      },
    },
    position: 48,
  },
  {
    display_name: "Close",
    id: 166,
    damage: 0,
    rarity: "special",
    tag: {
      display: {
        Lore: [],
      },
    },
    position: 49,
  },
  {
    display_name: "Next Page",
    id: 262,
    damage: 0,
    rarity: "uncommon",
    tag: {
      display: {
        Lore: [],
      },
    },
    position: 53,
  },
];

export const MUSEUM = {
  weapons: [
    "FANCY_SWORD",
    "UNDEAD_SWORD",
    "SPIDER_SWORD",
    "ROGUE_SWORD",
    "ASPECT_OF_THE_JERRY",
    "CLEAVER",
    "END_SWORD",
    "SQUIRE_SWORD",
    "CELESTE_WAND",
    "ARTISANAL_SHORTBOW",
    "PRISMARINE_BOW",
    "WITHER_BOW",
    "PRISMARINE_BLADE",
    "HUNTER_KNIFE",
    "UNDEAD_BOW",
    "CRYPT_DREADLORD_SWORD",
    "SNIPER_BOW",
    "RECLUSE_FANG",
    "STARLIGHT_WAND",
    "SUPER_CLEAVER",
    "TRIBAL_SPEAR",
    "HYPER_CLEAVER",
    "SUPER_UNDEAD_BOW",
    "ARACK",
    "FLAMING_SWORD",
    "DECENT_BOW",
    "VOIDWALKER_KATANA",
    "SAVANA_BOW",
    "ZOMBIE_SOLDIER_CUTLASS",
    "CONJURING_SWORD",
    "MERCENARY_AXE",
    "ENDER_BOW",
    "MACHINE_GUN_BOW",
    "TACTICIAN_SWORD",
    "CRYPT_BOW",
    "DEATH_BOW",
    "GIANT_CLEAVER",
    "ZOMBIE_COMMANDER_WHIP",
    "SHAMAN_SWORD",
    "ZOMBIE_KNIGHT_SWORD",
    "END_STONE_BOW",
    "SPIDER_QUEENS_STINGER",
    "SILVER_FANG",
    "REVENANT_SWORD",
    "ASPECT_OF_THE_END",
    "EDIBLE_MACE",
    "RAIDER_AXE",
    "SILENT_DEATH",
    "ZOMBIE_SWORD",
    "BLADE_OF_THE_VOLCANO",
    "GOLEM_SWORD",
    "STAFF_OF_THE_VOLCANO",
    "VENOMS_TOUCH",
    "DRAGON_SHORTBOW",
    "EMERALD_BLADE",
    "ORNATE_ZOMBIE_SWORD",
    "VOID_SWORD",
    "HURRICANE_BOW",
    "EARTH_SHARD",
    "GHOUL_BUSTER",
    "EXPLOSIVE_BOW",
    "END_STONE_SWORD",
    "SWORD_OF_BAD_HEALTH",
    "VOODOO_DOLL",
    "FROZEN_SCYTHE",
    "BONZO_STAFF",
    "VOIDEDGE_KATANA",
    "SOULS_REBOUND",
    "SLIME_BOW",
    "FIRE_FREEZE_STAFF",
    "LEAPING_SWORD",
    "STONE_BLADE",
    "FEL_SWORD",
    "FIRE_FURY_STAFF",
    "SCORPION_BOW",
    "SCORPION_FOIL",
    "SULPHUR_BOW",
    "SILK_EDGE_SWORD",
    "ASTRAEA",
    "HYPERION",
    "RUNIC_STAFF",
    "ASPECT_OF_THE_DRAGON",
    "FLORID_ZOMBIE_SWORD",
    "POOCH_SWORD",
    "SCYLLA",
    "HOLLOW_WAND",
    "VALKYRIE",
    "PHANTOM_ROD",
    "FIREDUST_DAGGER",
    "MAWDUST_DAGGER",
    "RAGNAROCK_AXE",
    "ASPECT_OF_THE_VOID",
    "PUMPKIN_LAUNCHER",
    "WAND_OF_STRENGTH",
    "INK_WAND",
    "VOODOO_DOLL_WILTED",
    "FLOWER_OF_TRUTH",
    "RUNAANS_BOW",
    "LIVID_DAGGER",
    "MIDAS_SWORD",
    "VORPAL_KATANA",
    "FIRE_VEIL_WAND",
    "SPIRIT_SWORD",
    "REAPER_SWORD",
    "SINSEEKER_SCYTHE",
    "WITHER_CLOAK",
    "JUJU_SHORTBOW",
    "YETI_SWORD",
    "SOUL_WHIP",
    "NECROMANCER_SWORD",
    "ALCHEMISTS_STAFF",
    "ICE_SPRAY_WAND",
    "SWORD_OF_REVELATIONS",
    "BONE_REAVER",
    "MOSQUITO_BOW",
    "LAST_BREATH",
    "REAPER_SCYTHE",
    "PIGMAN_SWORD",
    "ITEM_SPIRIT_BOW",
    "BOUQUET_OF_LIES",
    "GEMSTONE_GAUNTLET",
    "BONE_BOOMERANG",
    "FELTHORN_REAPER",
    "BAT_WAND",
    "SHADOW_FURY",
    "GLACIAL_SCYTHE",
    "BURSTMAW_DAGGER",
    "BURSTFIRE_DAGGER",
    "DAEDALUS_AXE",
    "ATOMSPLIT_KATANA",
    "AXE_OF_THE_SHREDDED",
    "GIANTS_SWORD",
    "MIDAS_STAFF",
    "TERMINATOR",
    "NECRON_BLADE",
    "HEARTMAW_DAGGER",
    "HEARTFIRE_DAGGER",
    "DARK_CLAYMORE",
  ],
  armor: [
    "FARM_SUIT",
    "CELESTE",
    "SQUIRE",
    "ROSETTA",
    "MERCENARY",
    "LEAFLET",
    "ANGLER",
    "PUMPKIN",
    "MUSHROOM",
    "CACTUS",
    "HEAT",
    "ROTTEN",
    "STARLIGHT",
    "FAIRY",
    "MINER_OUTFIT",
    "MITHRIL",
    "LAPIS_ARMOR",
    "FISHERMAN",
    "TANK_MINER",
    "SALMON_NEW",
    "GOLEM_ARMOR",
    "GROWTH",
    "HEAVY",
    "FARM_ARMOR",
    "HARDENED_DIAMOND",
    "SKELETON_MASTER",
    "ZOMBIE_SOLDIER",
    "SUPER_HEAVY",
    "ARMOR_OF_YOG",
    "FLAME_BREAKER",
    "END",
    "SKELETON_GRUNT",
    "SKELETON_SOLDIER",
    "CHEAP_TUXEDO",
    "MELON",
    "PARTY",
    "SEYMOUR",
    "ARACHNE",
    "MONSTER_HUNTER",
    "MONSTER_RAIDER",
    "BOUNCY",
    "TITANIUM",
    "LOTUS",
    "GOBLIN",
    "MINERAL",
    "ZOMBIE",
    "GLACITE",
    "FANCY_TUXEDO",
    "CRIMSON_HUNTER",
    "SPEEDSTER",
    "SKELETOR",
    "GEMSTONE",
    "EMERALD_ARMOR",
    "REVENANT",
    "CROPIE",
    "ICHTHYIC",
    "RAMPART",
    "SPONGE",
    "SNOW_SUIT",
    "TARANTULA",
    "CRYSTAL",
    "SPEED_WITHER",
    "POWER_WITHER",
    "WISE_WITHER",
    "ELEGANT_TUXEDO",
    "TANK_WITHER",
    "ARMOR_OF_THE_PACK",
    "CRIMSON_HUNTER",
    "ZOMBIE_KNIGHT",
    "ADAPTIVE",
    "SPOOKY",
    "SHARK_SCALE",
    "GLOSSY_MINERAL",
    "WEREWOLF",
    "BAT_PERSON",
    "REAPER",
    "RABBIT",
    "VANQUISHED",
    "MASTIFF",
    "ZOMBIE_COMMANDER",
    "PERFECT_TIER_12",
    "FINAL_DESTINATION",
    "SQUASH",
    "BRONZE_HUNTER",
    "LAVA_SEA_CREATURE",
    "SHADOW_ASSASSIN",
    "SKELETON_LORD",
    "FINWAVE",
    "MOLTEN",
    "ZOMBIE_LORD",
    "REKINDLED_EMBER",
    "FROZEN_BLAZE",
    "WITHER",
    "SORROW",
    "HOLY_DRAGON",
    "WISE_DRAGON",
    "NUTCRACKER",
    "HOLLOW",
    "OLD_DRAGON",
    "UNSTABLE_DRAGON",
    "DIVER",
    "FERVOR",
    "TERROR",
    "YOUNG_DRAGON",
    "PROTECTOR_DRAGON",
    "CRIMSON",
    "PERFECT_TIER_13",
    "AURORA",
    "STRONG_DRAGON",
    "SILVER_HUNTER",
    "FERMENTO",
    "NECROMANCER_LORD",
    "BERSERKER",
    "THUNDER",
    "GILLSPLASH",
    "SUPERIOR_DRAGON",
    "SHIMMERING_LIGHT",
    "GOLD_HUNTER",
    "DIVAN",
    "MAGMA_LORD",
    "DIAMOND_HUNTER",
  ],
  rarities: [
    "SQUID_HAT",
    "FISH_HAT",
    "ZOMBIE_HAT",
    "PUFFERFISH_HAT",
    "CHICKEN_HEAD",
    "FLINT_SHOVEL",
    "DOJO_WHITE_BELT",
    "CREEPER_HAT",
    "ROOKIE_AXE",
    "COW_HEAD",
    "SPIDER_HAT",
    "ROOKIE_HOE",
    "SLIME_HAT",
    "SKELETON_HAT",
    "CLOWNFISH_HAT",
    "EFFICIENT_AXE",
    "PROMISING_SPADE",
    "BLOBFISH_HAT",
    "MAGMA_FISH_HAT",
    "PROMISING_AXE",
    "SNOW_CANNON",
    "SKYMART_VACUUM",
    "PRISMARINE_ROD",
    "SPONGE_ROD",
    "SCULPTORS_AXE",
    "ZOMBIE_PICKAXE",
    "ROOKIE_PICKAXE",
    "SAM_SCYTHE",
    "SWEET_AXE",
    "RUSTY_TITANIUM_PICKAXE",
    "SPRAYONATOR",
    "RADIANT_POWER_ORB",
    "SQUID_BOOTS",
    "JUNGLE_AXE",
    "WAND_OF_HEALING",
    "LAPIS_PICKAXE",
    "SALMON_MASK",
    "BASIC_GARDENING_AXE",
    "BANDAGED_MITHRIL_PICKAXE",
    "MITHRIL_PICKAXE",
    "BASIC_GARDENING_HOE",
    "ENDERMAN_MASK",
    "SKYMART_TURBO_VACUUM",
    "GARDEN_SCYTHE",
    "ZOMBIE_MASK",
    "PROMISING_PICKAXE",
    "DOJO_GREEN_BELT",
    "FRACTURED_MITHRIL_PICKAXE",
    "SPEEDSTER_ROD",
    "DOJO_YELLOW_BELT",
    "WAND_OF_MENDING",
    "WINTER_ROD",
    "MENDER_HELMET",
    "STONE_CHESTPLATE",
    "DOJO_BLUE_BELT",
    "CHALLENGE_ROD",
    "DARK_GOGGLES",
    "MUSIC_PANTS",
    "SHADOW_GOGGLES",
    "MENDER_FEDORA",
    "METAL_CHESTPLATE",
    "SNOW_BLASTER",
    "KALHUIKI_MASK",
    "JUNGLE_PICKAXE",
    "LUMINOUS_BRACELET",
    "ENCHANTED_JACK_O_LANTERN",
    "RABBIT_HAT",
    "FARMER_ROD",
    "SNOWMAN_MASK",
    "TITANIUM_PICKAXE",
    "SNIPER_HELMET",
    "PARROT_MASK",
    "CHUM_ROD",
    "FALLEN_STAR_HAT",
    "REFINED_MITHRIL_PICKAXE",
    "ZOMBIE_HEART",
    "ARMADILLO_MASK",
    "ADVANCED_GARDENING_HOE",
    "ADVANCED_GARDENING_AXE",
    "CHAMP_ROD",
    "SYNTHESIZER_V1",
    "STONK_PICKAXE",
    "DOJO_BROWN_BELT",
    "SNOW_HOWITZER",
    "THEORETICAL_HOE_WHEAT_1",
    "THEORETICAL_HOE_CANE_1",
    "THEORETICAL_HOE_POTATO_1",
    "THEORETICAL_HOE_WARTS_1",
    "THEORETICAL_HOE_CARROT_1",
    "FARMER_BOOTS",
    "WARNING_FLARE",
    "STARTER_LAVA_ROD",
    "WITCH_MASK",
    "SOUL_ESOWARD",
    "SKYMART_HYPER_VACUUM",
    "CRYSTALLIZED_HEART",
    "BALLOON_SNAKE",
    "ICE_ROD",
    "MANA_FLUX_POWER_ORB",
    "VAMPIRE_MASK",
    "WEIRD_TUBA",
    "REFINED_TITANIUM_PICKAXE",
    "BONZO_MASK",
    "GEMSTONE_DRILL_1",
    "PEST_VEST",
    "DRAGONFUSE_GLOVE",
    "BEE_MASK",
    "FUNGI_CUTTER",
    "MELON_DICER",
    "PELT_BELT",
    "TREECAPITATOR_AXE",
    "PUMPKIN_DICER",
    "FROG_MASK",
    "OBSIDIAN_CHESTPLATE",
    "WATER_HYDRA_HEAD",
    "RANCHERS_BOOTS",
    "CACTUS_KNIFE",
    "VAMPIRE_WITCH_MASK",
    "WAND_OF_RESTORATION",
    "COCO_CHOPPER",
    "MITHRIL_COAT",
    "DRAGONFADE_CLOAK",
    "THEORETICAL_HOE_WHEAT_2",
    "THEORETICAL_HOE_CANE_2",
    "THEORETICAL_HOE_POTATO_2",
    "THEORETICAL_HOE_WARTS_2",
    "THEORETICAL_HOE_CARROT_2",
    "GHOST_BOOTS",
    "GEMSTONE_DRILL_2",
    "LEGEND_ROD",
    "SYNTHESIZER_V2",
    "THORNS_BOOTS",
    "MELON_DICER_2",
    "PUMPKIN_DICER_2",
    "KRAMPUS_HELMET",
    "WEIRDER_TUBA",
    "GLOOMLOCK_GRIMOIRE",
    "RIFT_NECKLACE_OUTSIDE",
    "GOLD_LIVID_HEAD",
    "GOLD_BONZO_HEAD",
    "GOLD_THORN_HEAD",
    "GOLD_PROFESSOR_HEAD",
    "GOLD_SADAN_HEAD",
    "GOLD_NECRON_HEAD",
    "GOLD_SCARF_HEAD",
    "POLISHED_TOPAZ_ROD",
    "MITHRIL_DRILL_1",
    "MAGMA_ROD",
    "STEEL_CHESTPLATE",
    "SOULWEAVER_GLOVES",
    "INFINI_VACUUM",
    "BONE_NECKLACE",
    "JERRY_STAFF",
    "MENDER_CROWN",
    "WITHER_GOGGLES",
    "YETI_ROD",
    "REVIVED_HEART",
    "CROWN_OF_GREED",
    "GEMSTONE_DRILL_3",
    "THE_SHREDDER",
    "THEORETICAL_HOE_WHEAT_3",
    "THEORETICAL_HOE_CANE_3",
    "THEORETICAL_HOE_POTATO_3",
    "THEORETICAL_HOE_WARTS_3",
    "REINFORCED_CHISEL",
    "THEORETICAL_HOE_CARROT_3",
    "SUMMONING_RING",
    "ANCIENT_CLOAK",
    "DELIRIUM_NECKLACE",
    "GYROKINETIC_WAND",
    "DESTRUCTION_CLOAK",
    "MELON_DICER_3",
    "PUMPKIN_DICER_3",
    "AUGER_ROD",
    "INFINI_VACUUM_HOOVERIUS",
    "ROD_OF_THE_SEA",
    "REAPER_MASK",
    "WAND_OF_ATONEMENT",
    "MITHRIL_DRILL_2",
    "SCOVILLE_BELT",
    "ALERT_FLARE",
    "IMPLOSION_BELT",
    "INFERNO_ROD",
    "DWARVEN_HANDWARMERS",
    "SCOURGE_CLOAK",
    "OVERFLUX_POWER_ORB",
    "SPIRIT_MASK",
    "LAVA_SHELL_NECKLACE",
    "GLACITE_CHISEL",
    "TITANIUM_DRILL_1",
    "GEMSTONE_DRILL_4",
    "GAUNTLET_OF_CONTAGION",
    "CROWN_OF_AVARICE",
    "DIAMOND_PROFESSOR_HEAD",
    "DIAMOND_SADAN_HEAD",
    "DIAMOND_LIVID_HEAD",
    "DIAMOND_NECRON_HEAD",
    "DIAMOND_SCARF_HEAD",
    "DIAMOND_BONZO_HEAD",
    "DIAMOND_THORN_HEAD",
    "DEMONLORD_GAUNTLET",
    "DOJO_BLACK_BELT",
    "WARDEN_HELMET",
    "PRECURSOR_EYE",
    "TACTICAL_INSERTION",
    "SYNTHESIZER_V3",
    "FLAMING_FIST",
    "TITANIUM_DRILL_3",
    "TITANIUM_DRILL_2",
    "PLASMAFLUX_POWER_ORB",
    "PERFECT_CHISEL",
    "ZORROS_CAPE",
    "BLAZETEKK_HAM_RADIO",
    "ANNIHILATION_CLOAK",
    "HELLFIRE_ROD",
    "TITANIUM_DRILL_4",
    "SOS_FLARE",
    "DIVAN_PENDANT",
    "DIVAN_DRILL",
  ],
  children: {
    TITANIUM: "MITHRIL",
    HEAT: "TANK_MINER",
    MASTIFF: "GROWTH",
    MINERAL: "HARDENED_DIAMOND",
    ARMOR_OF_YOG: "FLAME_BREAKER",
    FANCY_TUXEDO: "CHEAP_TUXEDO",
    CROPIE: "MELON",
    MONSTER_RAIDER: "MONSTER_HUNTER",
    GLOSSY_MINERAL: "MINERAL",
    REVENANT: "ZOMBIE",
    ELEGANT_TUXEDO: "FANCY_TUXEDO",
    VANQUISHED: "CRIMSON_HUNTER",
    REAPER: "REVENANT",
    SQUASH: "CROPIE",
    FINWAVE: "ICHTHYIC",
    SHARK_SCALE: "SPONGE",
    NUTCRACKER: "SNOW_SUIT",
    POWER_WITHER: "SPEED_WITHER",
    SPEED_WITHER: "WISE_WITHER",
    WISE_WITHER: "TANK_WITHER",
    FROZEN_BLAZE: "BLAZE",
    BAT_PERSON: "SPOOKY",
    PERFECT_TIER_13: "PERFECT_TIER_12",
    FERMENTO: "SQUASH",
    SILVER_HUNTER: "BRONZE_HUNTER",
    GILLSPLASH: "FINWAVE",
    TANK_WITHER: "WITHER",
    GOLD_HUNTER: "SILVER_HUNTER",
    DIAMOND_HUNTER: "GOLD_HUNTER",
  },
  armor_to_id: {
    FARM_SUIT: "FARM_SUIT_HELMET",
    CELESTE: "CELESTE_HELMET",
    SQUIRE: "SQUIRE_HELMET",
    ROSETTA: "ROSETTA_HELMET",
    MERCENARY: "MERCENARY_HELMET",
    LEAFLET: "LEAFLET_HELMET",
    ANGLER: "ANGLER_HELMET",
    PUMPKIN: "PUMPKIN_HELMET",
    MUSHROOM: "MUSHROOM_HELMET",
    CACTUS: "CACTUS_HELMET",
    HEAT: "HEAT_HELMET",
    ROTTEN: "ROTTEN_HELMET",
    STARLIGHT: "STARLIGHT_HELMET",
    FAIRY: "FAIRY_HELMET",
    MINER_OUTFIT: "MINER_OUTFIT_HELMET",
    MITHRIL: "MITHRIL_NECKLACE",
    LAPIS_ARMOR: "LAPIS_ARMOR_HELMET",
    FISHERMAN: "PRISMARINE_NECKLACE",
    TANK_MINER: "TANK_MINER_HELMET",
    SALMON_NEW: "SALMON_HELMET_NEW",
    GOLEM_ARMOR: "GOLEM_ARMOR_HELMET",
    GROWTH: "GROWTH_HELMET",
    HEAVY: "HEAVY_HELMET",
    FARM_ARMOR: "FARM_ARMOR_HELMET",
    HARDENED_DIAMOND: "HARDENED_DIAMOND_HELMET",
    SKELETON_MASTER: "SKELETON_MASTER_HELMET",
    ZOMBIE_SOLDIER: "ZOMBIE_SOLDIER_HELMET",
    SUPER_HEAVY: "SUPER_HEAVY_HELMET",
    ARMOR_OF_YOG: "ARMOR_OF_YOG_HELMET",
    FLAME_BREAKER: "FLAME_BREAKER_HELMET",
    END: "END_HELMET",
    SKELETON_GRUNT: "SKELETON_GRUNT_HELMET",
    SKELETON_SOLDIER: "SKELETON_SOLDIER_HELMET",
    CHEAP_TUXEDO: "CHEAP_TUXEDO_CHESTPLATE",
    MELON: "MELON_HELMET",
    PARTY: "PARTY_NECKLACE",
    SEYMOUR: "CASHMERE_JACKET",
    ARACHNE: "ARACHNE_HELMET",
    MONSTER_HUNTER: "SKELETON_HELMET",
    MONSTER_RAIDER: "TARANTULA_BOOTS",
    BOUNCY: "BOUNCY_HELMET",
    TITANIUM: "TITANIUM_NECKLACE",
    LOTUS: "LOTUS_NECKLACE",
    GOBLIN: "GOBLIN_HELMET",
    MINERAL: "MINERAL_HELMET",
    ZOMBIE: "ZOMBIE_CHESTPLATE",
    GLACITE: "GLACITE_HELMET",
    FANCY_TUXEDO: "FANCY_TUXEDO_CHESTPLATE",
    CRIMSON_HUNTER: "BLAZE_HELMET",
    SPEEDSTER: "SPEEDSTER_HELMET",
    SKELETOR: "SKELETOR_HELMET",
    GEMSTONE: "AMBER_NECKLACE",
    EMERALD_ARMOR: "EMERALD_ARMOR_HELMET",
    REVENANT: "REVENANT_CHESTPLATE",
    CROPIE: "CROPIE_HELMET",
    ICHTHYIC: "ICHTHYIC_CLOAK",
    RAMPART: "RAMPART_HELMET",
    SPONGE: "SPONGE_HELMET",
    SNOW_SUIT: "SNOW_SUIT_HELMET",
    TARANTULA: "TARANTULA_HELMET",
    CRYSTAL: "CRYSTAL_HELMET",
    SPEED_WITHER: "SPEED_WITHER_HELMET",
    POWER_WITHER: "POWER_WITHER_HELMET",
    WISE_WITHER: "WISE_WITHER_HELMET",
    ELEGANT_TUXEDO: "ELEGANT_TUXEDO_CHESTPLATE",
    TANK_WITHER: "TANK_WITHER_HELMET",
    ARMOR_OF_THE_PACK: "HELMET_OF_THE_PACK",
    ZOMBIE_KNIGHT: "ZOMBIE_KNIGHT_HELMET",
    ADAPTIVE: "ADAPTIVE_HELMET",
    SPOOKY: "SPOOKY_HELMET",
    SHARK_SCALE: "SHARK_SCALE_HELMET",
    GLOSSY_MINERAL: "GLOSSY_MINERAL_HELMET",
    WEREWOLF: "WEREWOLF_HELMET",
    BAT_PERSON: "BAT_PERSON_HELMET",
    REAPER: "REAPER_CHESTPLATE",
    RABBIT: "RABBIT_HELMET",
    VANQUISHED: "VANQUISHED_MAGMA_NECKLACE",
    MASTIFF: "MASTIFF_HELMET",
    ZOMBIE_COMMANDER: "ZOMBIE_COMMANDER_HELMET",
    PERFECT_TIER_12: "PERFECT_HELMET_12",
    FINAL_DESTINATION: "FINAL_DESTINATION_HELMET",
    SQUASH: "SQUASH_HELMET",
    BRONZE_HUNTER: "BRONZE_HUNTER_HELMET",
    LAVA_SEA_CREATURE: "TAURUS_HELMET",
    SHADOW_ASSASSIN: "SHADOW_ASSASSIN_HELMET",
    SKELETON_LORD: "SKELETON_LORD_HELMET",
    FINWAVE: "FINWAVE_CLOAK",
    MOLTEN: "MOLTEN_NECKLACE",
    ZOMBIE_LORD: "ZOMBIE_LORD_HELMET",
    REKINDLED_EMBER: "REKINDLED_EMBER_HELMET",
    FROZEN_BLAZE: "FROZEN_BLAZE_HELMET",
    WITHER: "WITHER_HELMET",
    SORROW: "SORROW_HELMET",
    HOLY_DRAGON: "HOLY_DRAGON_HELMET",
    WISE_DRAGON: "WISE_DRAGON_HELMET",
    NUTCRACKER: "NUTCRACKER_HELMET",
    HOLLOW: "HOLLOW_HELMET",
    OLD_DRAGON: "OLD_DRAGON_HELMET",
    UNSTABLE_DRAGON: "UNSTABLE_DRAGON_HELMET",
    DIVER: "DIVER_HELMET",
    FERVOR: "FERVOR_HELMET",
    TERROR: "TERROR_HELMET",
    YOUNG_DRAGON: "YOUNG_DRAGON_HELMET",
    PROTECTOR_DRAGON: "PROTECTOR_DRAGON_HELMET",
    CRIMSON: "CRIMSON_HELMET",
    PERFECT_TIER_13: "PERFECT_HELMET_13",
    AURORA: "AURORA_HELMET",
    STRONG_DRAGON: "STRONG_DRAGON_HELMET",
    SILVER_HUNTER: "SILVER_HUNTER_HELMET",
    FERMENTO: "FERMENTO_HELMET",
    NECROMANCER_LORD: "NECROMANCER_LORD_HELMET",
    BERSERKER: "BERSERKER_HELMET",
    THUNDER: "THUNDER_HELMET",
    GILLSPLASH: "GILLSPLASH_CLOAK",
    SUPERIOR_DRAGON: "SUPERIOR_DRAGON_HELMET",
    SHIMMERING_LIGHT: "SHIMMERING_LIGHT_HOOD",
    GOLD_HUNTER: "GOLD_HUNTER_HELMET",
    DIVAN: "DIVAN_HELMET",
    MAGMA_LORD: "MAGMA_LORD_HELMET",
    DIAMOND_HUNTER: "DIAMOND_HUNTER_HELMET",
  },
  inventory: [
    {
      display_name: "Museum",
      rarity: "rare",
      texture_path: "/head/438cf3f8e54afc3b3f91d20a49f324dca1486007fe545399055524c17941f4dc",
      tag: {
        display: {
          Lore: [
            "§7The §9Museum §7is a compendium",
            "§7of all of your items in",
            "§7SkyBlock. Donate items to your",
            "§7Museum to unlock rewards.",
            "",
            "§7Other players can visit your",
            "§7Museum at any time! Display your",
            "§7best items proudly for all to",
            "§7see.",
            "",
          ],
        },
      },
      position: 4,
      progressType: "total",
    },
    {
      display_name: "Weapons",
      id: 276,
      damage: 0,
      rarity: "uncommon",
      tag: {
        display: {
          Lore: ["§7View all of the §6Weapons §7that", "§7you have donated to the", "§7§9Museum§7!", ""],
        },
      },
      position: 19,
      inventoryType: "weapons",
      containsItems: [
        {
          display_name: "Weapons",
          id: 276,
          damage: 0,
          rarity: "uncommon",
          tag: {
            display: {
              Lore: ["§7View all of the §6Weapons §7that", "§7you have donated to the", "§7§9Museum§7!", ""],
            },
          },
          position: 4,
        },
        ...categoryInventory,
      ],
      numPagesContainsInventory: 1,
      progressType: "weapons",
    },
    {
      display_name: "Armor Sets",
      id: 311,
      damage: 0,
      rarity: "uncommon",
      tag: {
        display: {
          Lore: ["§7View all of the §9Armor Sets", "§9§7that you have donated to the", "§7§9Museum§7!", ""],
        },
      },
      position: 21,
      inventoryType: "armor",
      containsItems: [
        {
          display_name: "Armor Sets",
          id: 311,
          damage: 0,
          rarity: "uncommon",
          tag: {
            display: {
              Lore: ["§7View all of the §9Armor Sets", "§9§7that you have donated to the", "§7§9Museum§7!", ""],
            },
          },
          position: 4,
        },
        ...categoryInventory,
      ],
      numPagesContainsInventory: 1,
      progressType: "armor",
    },
    {
      display: "Rarities",
      rarity: "uncommon",
      texture_path: "/head/86addbd5dedad40999473be4a7f48f6236a79a0dce971b5dbd7372014ae394d",
      tag: {
        display: {
          Lore: ["§7View all of the §5Rarities", "§5§7that you have donated to the", "§7§9Museum§7!", ""],
        },
      },
      position: 23,
      inventoryType: "rarities",
      containsItems: [
        {
          display: "Rarities",
          rarity: "uncommon",
          texture_path: "/head/86addbd5dedad40999473be4a7f48f6236a79a0dce971b5dbd7372014ae394d",
          tag: {
            display: {
              Lore: ["§7View all of the §5Rarities", "§5§7that you have donated to the", "§7§9Museum§7!", ""],
            },
          },
          position: 4,
        },
        ...categoryInventory,
      ],
      numPagesContainsInventory: 1,
      progressType: "rarities",
    },
    {
      display_name: "Special Items",
      id: 354,
      damage: 0,
      rarity: "uncommon",
      tag: {
        display: {
          Lore: [
            "§7View all of the §dSpecial Items",
            "§d§7that you have donated to the",
            "§7§9Museum§7!",
            "",
            "§7These items don't count towards",
            "§7Museum progress and rewards, but",
            "§7are cool nonetheless. Items that",
            "§7are §9rare §7and §6prestigious",
            "§6§7fit into this category, and",
            "§7can be displayed in the Main",
            "§7room of the Museum.",
            "",
          ],
        },
      },
      position: 25,
      inventoryType: "special",
      containsItems: [
        {
          display_name: "Special Items",
          id: 354,
          damage: 0,
          rarity: "uncommon",
          tag: {
            display: {
              Lore: [
                "§7View all of the §dSpecial Items",
                "§d§7that you have donated to the",
                "§7§9Museum§7!",
                "",
                "§7These items don't count towards",
                "§7Museum progress and rewards, but",
                "§7are cool nonetheless. Items that",
                "§7are §9rare §7and §6prestigious",
                "§6§7fit into this category, and",
                "§7can be displayed in the Main",
                "§7room of the Museum.",
                "",
              ],
            },
          },
          position: 4,
        },
        ...categoryInventory,
      ],
      numPagesContainsInventory: 1,
      progressType: "special",
    },
    {
      display_name: "Museum Appraisal",
      id: 264,
      damage: 0,
      rarity: "legendary",
      tag: {
        display: {
          Lore: [
            "§7§6Madame Goldsworth §7offers an",
            "§7appraisal service for Museums.",
            "§7When unlocked, she will appraise",
            "§7the value of your Museum each",
            "§7time you add or remove items.",
            "",
            "§7This service also allows you to",
            "§7appear on the §6Top Valued",
            "§6§7filter in the §9Museum",
            "§9Browser§7.",
            "",
          ],
        },
      },
      position: 40,
      progressType: "appraisal",
    },
    {
      display_name: "Edit NPC Tags",
      id: 421,
      damage: 0,
      rarity: "uncommon",
      tag: {
        display: {
          Lore: [
            "§7Edit the tags that appear above",
            "§7your NPC. Show off your SkyBlock",
            "§7progress with tags showing your",
            "§7highest collection, best Skill,",
            "§7and more!",
            "",
            "§cCOMING SOON",
          ],
        },
      },
      position: 45,
    },
    {
      display_name: "Museum Rewards",
      id: 41,
      damage: 0,
      rarity: "legendary",
      tag: {
        display: {
          Lore: [
            "§7Each time you donate an item to",
            "§7your Museum, the §bCurator",
            "§b§7will reward you.",
            "",
            "§7§dSpecial Items §7do not count",
            "§7towards your Museum rewards",
            "§7progress.",
            "",
            "§7Currently, most rewards are",
            "§7§ccoming soon§7, but you can",
            "§7view them anyway.",
          ],
        },
      },
      position: 48,
    },
    {
      display_name: "Close",
      id: 166,
      damage: 0,
      rarity: "special",
      tag: {
        display: {
          Lore: [],
        },
      },
      position: 49,
    },
    {
      display_name: "Museum Browser",
      id: 323,
      damage: 0,
      rarity: "uncommon",
      tag: {
        display: {
          Lore: ["§7View the Museums of your", "§7friends, top valued players, and", "§7more!"],
        },
      },
      position: 50,
    },
  ],
  item_slots: [
    10, 11, 12, 13, 14, 15, 16, 19, 20, 21, 22, 23, 24, 25, 28, 29, 30, 31, 32, 33, 34, 37, 38, 39, 40, 41, 42, 43,
  ],
  missing_item: {
    weapons: {
      display_name: null,
      id: 351,
      damage: 8,
      rarity: "special",
      tag: {
        display: {
          Lore: ["§7Click on this item in your", "§7inventory to add it to your", "§7§9Museum§7!"],
        },
      },
    },
    armor: {
      display_name: null,
      id: 351,
      damage: 8,
      rarity: "special",
      tag: {
        display: {
          Lore: [
            "§7Click on an armor piece in your",
            "§7inventory that belongs to this",
            "§7armor set to donate the full set",
            "§7to your Museum.",
          ],
        },
      },
    },
    rarities: {
      display_name: null,
      id: 351,
      damage: 8,
      rarity: "special",
      tag: {
        display: {
          Lore: ["§7Click on this item in your", "§7inventory to add it to your", "§7§9Museum§7!"],
        },
      },
    },
    special: null,
  },
  higher_tier_donated: {
    display_name: null,
    id: 351,
    damage: 10,
    rarity: "special",
    tag: {
      display: {
        Lore: ["§7Donated as higher tier"],
      },
    },
  },
};

export function getMuseumItems() {
  const { armor, weapons, rarities } = MUSEUM;

  return [...armor, ...weapons, ...rarities];
}
